# Generated by Django 4.2.11 on 2026-04-04 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tanks', '0001_initial'),
        ('pumps', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrecord',
            name='pompiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrecord',
            name='pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_records', to='pumps.pump'),
        ),
        migrations.AddField(
            model_name='pump',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pumps', to='tanks.tank'),
        ),
    ]
