# Generated by Django 4.2.11 on 2026-04-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tank name')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol/Premium')], max_length=10, verbose_name='fuel type')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='capacity (L)')),
                ('current_level', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current level (L)')),
                ('minimum_threshold', models.DecimalField(decimal_places=2, help_text='Alert when level drops below this value', max_digits=10, verbose_name='minimum threshold (L)')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('critical', 'Critical'), ('empty', 'Empty')], default='normal', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tank',
                'verbose_name_plural': 'tanks',
                'ordering': ['branch', 'fuel_type'],
            },
        ),
        migrations.CreateModel(
            name='TankRestockingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='requested quantity (L)')),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='delivered quantity (L)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'restocking request',
                'verbose_name_plural': 'restocking requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
